################################################################################
#                                                                              #
#                              csv_translator.py                               #
#                                                                              #
################################################################################
#                                                                              #
#        This is a class for translating Land Cover data.                      #
#                                                                              #
#        Author(s): Abe Megahed                                                #
#                                                                              #
#        This file is subject to the terms and conditions defined in           #
#        'LICENSE.txt', which is part of this source code distribution.        #
#                                                                              #
################################################################################
#        Copyright (C) 2025 - Global Mosquito Observations Dashboard           #
################################################################################

import os

#
# globals
#

current = os.path.dirname(os.path.abspath(__file__))
schema = current + '/output_schema.txt'

#
# class
#

class LandCoverTranslator:
	columns = []
	count = 0

	#
	# constructor
	#

	def __init__(self):
		global schema

		# read schema
		#
		with open(schema, 'r') as file:
			for line in file:
				self.columns.append(line.replace(',', '').replace('REQUIRED', '').replace('MANDATORY', '').strip())

	#
	# getting methods
	#

	def get_observation_value(self, key, observation):

		"""
		Get a value with a particular name (key) from an observation.

		Args:
			observation (dict): The observation data.

		Returns:
			object: The value.
		"""

		match key:

			case 'OBJECTID':
				self.count += 1
				return self.count

			case 'title':
				return 'Globe Land Cover v1.0.0 OGC'

			case 'description':
				return 'Land Cover Data Generated by Globe'

			case 'dataStreamName':
				return 'Globe Land Cover v1.0.0.0 OGC' + observation['lc_organizationId'] + ':' + observation['lc_siteId'] + observation['lc_Userid']

			case 'dataStreamDescription':
				return {
					'title': 'Globe Land Cover v1.0.0 OGC', 
					'lc_LandCoverId': observation['lc_organizationId'], 
					'lc_siteId': observation['lc_siteId'], 
					'lc_Userid': observation['lc_Userid']
				}

			case 'observationType':
				return 'category'

			case 'unitOfCategory':
				return {
					"name": "classification", 
					"symbol": "none",
					"definition": "n/a",
					"sensor use": "yes"
				}

			case 'projectObservationUID':
				return observation['lc_pid'] + ':' + observation['lc_siteId']

			case 'phenomenonTime':
				return observation['lc_measuredDate']

			case 'resultTime':
				return observation['lc_MeasuredAt']

			case 'result':
				return {
					'lc_PrimaryClassification': 'NA', 
					'lc_SecondaryClassification': 'NA', 
					'lc_EastClassifications': '', 
					'lc_WestClassifications': '', 
					'lc_NorthClassifications': '', 
					'lc_SouthClassifications': ''
				}

			case 'submitTime':
				return observation['lc_createDate']

			case 'imageStatus':
				return 1

			case 'imageResult':
				return {
					'lc_UpwardPhotoUrl': observation['lc_UpwardPhotoUrl'], 
					'lc_DownwardPhotoUrl': observation['lc_DownwardPhotoUrl'], 
					'lc_EastPhotoUrl': observation['lc_EastPhotoUrl'], 
					'lc_WestPhotoUrl': observation['lc_WestPhotoUrl'], 
					'lc_NorthPhotoUrl': observation['lc_NorthPhotoUrl'], 
					'lc_SouthPhotoUrl': observation['lc_SouthPhotoUrl']
				}

			case 'lc_UpwardPhotoUrl':
				return observation['lc_UpwardPhotoUrl'],

			case 'lc_DownwardPhotoUrl':
				return observation['lc_DownwardPhotoUrl'],

			case 'lc_EastPhotoUrl':
				return observation['lc_EastPhotoUrl'], 

			case 'lc_WestPhotoUrl':
				return observation['lc_WestPhotoUrl'],

			case 'lc_NorthPhotoUrl':
				return observation['lc_NorthPhotoUrl'], 

			case 'lc_SouthPhotoUrl':
				return observation['lc_SouthPhotoUrl']

			case 'parameters':
				return {
					'lc_DownwardCaption': observation['lc_DownwardCaption'], 
					'lc_DownwardExtraData': observation['lc_DownwardExtraData'], 
					'lc_EastCaption': observation['lc_EastCaption'], 
					'lc_EastExtraData': observation['lc_EastExtraData'], 
					'lc_NorthCaption': observation['lc_NorthCaption'], 
					'lc_NorthExtraData': observation['lc_NorthExtraData'], 
					'lc_SouthCaption': observation['lc_SouthCaption'], 
					'lc_SouthExtraData': observation['lc_SouthExtraData'], 
					'lc_UpwardCaption': observation['lc_UpwardCaption'], 
					'lc_UpwardExtraData': observation['lc_UpwardExtraData'], 
					'lc_WestCaption': observation['lc_WestCaption'], 
					'lc_WestExtraData': observation['lc_WestExtraData'], 
					'lc_MGRSLatitude': observation['lc_MGRSLatitude'],  
					'lc_MGRSLongitude': observation['lc_MGRSLongitude'], 
					'lc_elevation': observation['lc_elevation'], 
					'lc_CumulativeCompletenessScore': observation['lc_CumulativeCompletenessScore'],  
					'lc_SubCompletenessScore': observation['lc_SubCompletenessScore'],  
					'lc_LocationAccuracyM': observation['lc_LocationAccuracyM'],  
					'lc_LocationMethod': observation['lc_LocationMethod']
				}

			case 'licenseName':
				return 'NA'

			case 'licenseURI':
				return 'https://www.globe.gov/documents/10157/2592674/GLOBE+Data+User+Guide_v1_final.pdf/863a971d-95c5-4dd9-b75c-46713f019088'

			case 'attributionDataAggregator':
				return 'Global Learning and Observations to Benefit the Environment (GLOBE)'

			case 'validationStatus':
				return 1

			case 'validationMethod':
				return "Validation method is as follows: 1) GLOBE Observer App has its own validators to ensure the requested data type matches the received value. 2) GLOBE Observer Team validates the photos to ensure they are useful and match the area where the photographer took the photo. 3) Our pre-processing algorithms ensure values entered are appropriate and reasonable. Our code also creates quality assurance flags to allow Users to better summarize the data."

			case 'validationResult':
				return "FALSE - Entries with their photos undergoing GLOBE validation process will have a 'pending' code for their photos. NOTE: Some photos will be listed as 'rejected'. Photos that pass our validation process will include GLOBE's URL to that photo"

			case 'qualityDescription':
				return "GLOBE Observer Data Guide: https://www.globe.gov/documents/10157/2592674/GLOBE+Data+User+Guide_v1_final.pdf/863a971d-95c5-4dd9-b75c-46713f019088 (Page 25) | Our Code Documentation: https://iges-geospatial.github.io/globe-observer-utils-docs/go_utils/mhm.html"

			case 'qualityGrade':
				return 'research'

			case 'observedPropertyName':
				return 'Land Cover Photos'

			case 'observedPropertyDescription':
				return 'The primary and secondary Land Cover Classifications for an area'

			case 'observedPropertyDefinition':
				return 'Land Cover as documented by photographs'

			case 'sensorName':
				return 'NA'

			case 'sensorDescription':
				return 'NA'

			case 'locationName':
				return observation['lc_siteName']

			case 'locationDescription':
				return 'Site ID:' + observation['lc_siteId']

			case 'locationEncodingType':
				return 'GeoJSON'

			case 'latitude':
				return observation['lc_Latitude']

			case 'longitude':
				return observation['lc_Longitude']

			case 'elevation':
				return observation['lc_elevation']

			case 'thingName':
				return observation['lc_Userid'] + ':' + observation['lc_GlobeTeams'],

			case 'thingDescription':
				return {
					'lc_organizationName': observation['lc_organizationName'], 
					'lc_PhotoCount': observation['lc_PhotoCount'], 
					'lc_RejectedCount': observation['lc_RejectedCount'], 
					'lc_PendingCount': observation['lc_PendingCount'], 
					'lc_EmptyCount': observation['lc_EmptyCount']
				}

			case 'featureName':
				return observation['lc_siteName']

			case 'featureDescription':
				return ''

			case 'featureEncodingType':
				return 'GeoJSON'

			case 'featureLocation':
				return '[' + observation['lc_Latitude'] + ',' + observation['lc_Longitude'] + ']'

			case 'x':
				return observation['lc_Longitude']

			case 'y':
				return observation['lc_Latitude']

		return ''

	def get_observation_values(self, observation):

		"""
		Get a set of value from an observation.

		Args:
			observation (dict): The observation data.

		Returns:
			object: The set of values.
		"""

		values = []
		for column in self.columns:
			values.append(self.get_observation_value(column, observation))
		return values

	def get_observations_values(self, observations):

		"""
		Get array of sets of values from an array of observations.

		Args:
			observation (dict): The observation data.

		Returns:
			object: array of sets of values.
		"""

		values = []
		for observation in observations:
			values.append(self.get_observation_values(observation))
		return values